-- Table: public.Felhasznalo

-- DROP TABLE IF EXISTS public."Felhasznalo";

CREATE TABLE IF NOT EXISTS public."Felhasznalo"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    felhasznalonev text COLLATE pg_catalog."default" NOT NULL,
    jelszo text COLLATE pg_catalog."default",
    email text COLLATE pg_catalog."default",
    teljes_nev text COLLATE pg_catalog."default",
    szerep_tipus text COLLATE pg_catalog."default" NOT NULL,
    letrehozas_idopont timestamp without time zone DEFAULT now(),
    utolso_bejelentkezes timestamp without time zone,
    elerheto boolean DEFAULT true,
    aktiv boolean DEFAULT true,
    email_megerositve boolean NOT NULL DEFAULT false,
    email_megerosito_token text COLLATE pg_catalog."default",
    email_megerosites_hatarido timestamp without time zone,
    reaktivacio_token text COLLATE pg_catalog."default",
    reaktivacio_hatarido timestamp without time zone,
    CONSTRAINT "Felhasznalo_pkey" PRIMARY KEY (id),
    CONSTRAINT "Felhasznalo_email_key" UNIQUE (email),
    CONSTRAINT "Felhasznalo_felhasznalonev_key" UNIQUE (felhasznalonev)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Felhasznalo"
    OWNER to postgres;
-- Index: idx_felhasznalo_email_megerosito_token

-- DROP INDEX IF EXISTS public.idx_felhasznalo_email_megerosito_token;

CREATE INDEX IF NOT EXISTS idx_felhasznalo_email_megerosito_token
    ON public."Felhasznalo" USING btree
    (email_megerosito_token COLLATE pg_catalog."default" ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;

-- Table: public.Projekt

-- DROP TABLE IF EXISTS public."Projekt";

CREATE TABLE IF NOT EXISTS public."Projekt"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    projekt_nev text COLLATE pg_catalog."default" NOT NULL,
    leiras text COLLATE pg_catalog."default",
    letrehozo_id integer NOT NULL,
    statusz text COLLATE pg_catalog."default",
    letrehozas_idopont timestamp without time zone DEFAULT now(),
    hatarido timestamp without time zone,
    CONSTRAINT "Projekt_pkey" PRIMARY KEY (id),
    CONSTRAINT "Projekt_letrehozo_id_fkey" FOREIGN KEY (letrehozo_id)
        REFERENCES public."Felhasznalo" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Projekt"
    OWNER to postgres;


-- Table: public.Feladat

-- DROP TABLE IF EXISTS public."Feladat";

CREATE TABLE IF NOT EXISTS public."Feladat"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    projekt_id integer NOT NULL,
    feladat_nev text COLLATE pg_catalog."default" NOT NULL,
    feladat_leiras text COLLATE pg_catalog."default",
    letrehozo_id integer NOT NULL,
    felelos_id integer,
    prioritas text COLLATE pg_catalog."default" DEFAULT 'közepes'::text,
    statusz text COLLATE pg_catalog."default" DEFAULT 'folyamatban'::text,
    hatarido timestamp without time zone,
    letrehozas_idopont timestamp without time zone DEFAULT now(),
    modositas_idopont timestamp without time zone,
    CONSTRAINT "Feladat_pkey" PRIMARY KEY (id),
    CONSTRAINT "Feladat_letrehozo_id_fkey" FOREIGN KEY (letrehozo_id)
        REFERENCES public."Felhasznalo" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "Feladat_projekt_id_fkey" FOREIGN KEY (projekt_id)
        REFERENCES public."Projekt" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Feladat"
    OWNER to postgres;


-- Table: public.Beadas

-- DROP TABLE IF EXISTS public."Beadas";

CREATE TABLE IF NOT EXISTS public."Beadas"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    feladat_id integer NOT NULL,
    felhasznalo_id integer NOT NULL,
    tanar_id integer NOT NULL,
    pontszam integer,
    maxpontszam integer DEFAULT 100,
    jegy integer,
    statusz text COLLATE pg_catalog."default" DEFAULT 'hiányzik'::text,
    visszajelzes text COLLATE pg_catalog."default",
    bekuldes_idopont timestamp without time zone DEFAULT now(),
    ertekeles_idopont timestamp without time zone,
    CONSTRAINT "Beadas_pkey" PRIMARY KEY (id),
    CONSTRAINT "Beadas_feladat_id_fkey" FOREIGN KEY (feladat_id)
        REFERENCES public."Feladat" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "Beadas_felhasznalo_id_fkey" FOREIGN KEY (felhasznalo_id)
        REFERENCES public."Felhasznalo" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "Beadas_tanar_id_fkey" FOREIGN KEY (tanar_id)
        REFERENCES public."Felhasznalo" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Beadas"
    OWNER to postgres;


-- Table: public.FeladatKomment

-- DROP TABLE IF EXISTS public."FeladatKomment";

CREATE TABLE IF NOT EXISTS public."FeladatKomment"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    feladat_id integer NOT NULL,
    felhasznalo_id integer NOT NULL,
    komment_szoveg text COLLATE pg_catalog."default" NOT NULL,
    letrehozas_idopont timestamp without time zone DEFAULT now(),
    CONSTRAINT "FeladatKomment_pkey" PRIMARY KEY (id),
    CONSTRAINT "FeladatKomment_feladat_id_fkey" FOREIGN KEY (feladat_id)
        REFERENCES public."Feladat" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "FeladatKomment_felhasznalo_id_fkey" FOREIGN KEY (felhasznalo_id)
        REFERENCES public."Felhasznalo" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."FeladatKomment"
    OWNER to postgres;


-- Table: public.File

-- DROP TABLE IF EXISTS public."File";

CREATE TABLE IF NOT EXISTS public."File"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    beadas_id integer,
    felhasznalo_id integer NOT NULL,
    file_nev text COLLATE pg_catalog."default" NOT NULL,
    file_meret integer,
    file_tipus text COLLATE pg_catalog."default",
    feltoltes_idopont timestamp without time zone DEFAULT now(),
    file_eleresiut text COLLATE pg_catalog."default",
    CONSTRAINT "File_pkey" PRIMARY KEY (id),
    CONSTRAINT "File_beadas_id_fkey" FOREIGN KEY (beadas_id)
        REFERENCES public."Beadas" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "File_felhasznalo_id_fkey" FOREIGN KEY (felhasznalo_id)
        REFERENCES public."Felhasznalo" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."File"
    OWNER to postgres;


-- Table: public.Naplo

-- DROP TABLE IF EXISTS public."Naplo";

CREATE TABLE IF NOT EXISTS public."Naplo"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    felhasznalo_id integer NOT NULL,
    projekt_id integer,
    feladat_id integer,
    muvelet text COLLATE pg_catalog."default" NOT NULL,
    leiras text COLLATE pg_catalog."default",
    idopont timestamp without time zone DEFAULT now(),
    CONSTRAINT "Naplo_pkey" PRIMARY KEY (id),
    CONSTRAINT "Naplo_feladat_id_fkey" FOREIGN KEY (feladat_id)
        REFERENCES public."Feladat" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "Naplo_felhasznalo_id_fkey" FOREIGN KEY (felhasznalo_id)
        REFERENCES public."Felhasznalo" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "Naplo_projekt_id_fkey" FOREIGN KEY (projekt_id)
        REFERENCES public."Projekt" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Naplo"
    OWNER to postgres;


-- Table: public.ProjektTag

-- DROP TABLE IF EXISTS public."ProjektTag";

CREATE TABLE IF NOT EXISTS public."ProjektTag"
(
    projekt_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    felhasznalo_id integer NOT NULL,
    csatlakozas_idopont timestamp without time zone DEFAULT now(),
    CONSTRAINT "ProjektTag_pkey" PRIMARY KEY (projekt_id, felhasznalo_id),
    CONSTRAINT "ProjektTag_felhasznalo_id_fkey" FOREIGN KEY (felhasznalo_id)
        REFERENCES public."Felhasznalo" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "ProjektTag_projekt_id_fkey" FOREIGN KEY (projekt_id)
        REFERENCES public."Projekt" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."ProjektTag"
    OWNER to postgres;


-- Table: public.Statisztika

-- DROP TABLE IF EXISTS public."Statisztika";

CREATE TABLE IF NOT EXISTS public."Statisztika"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    felhasznalo_id integer,
    projekt_id integer,
    statisztika_nev text COLLATE pg_catalog."default" NOT NULL,
    ertek integer,
    meresi_idopont timestamp without time zone DEFAULT now(),
    pontszam integer,
    maxpontszam integer DEFAULT 100,
    CONSTRAINT "Statisztika_pkey" PRIMARY KEY (id),
    CONSTRAINT "Statisztika_felhasznalo_id_fkey" FOREIGN KEY (felhasznalo_id)
        REFERENCES public."Felhasznalo" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "Statisztika_projekt_id_fkey" FOREIGN KEY (projekt_id)
        REFERENCES public."Projekt" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Statisztika"
    OWNER to postgres;


-- Table: public.Uzenet

-- DROP TABLE IF EXISTS public."Uzenet";

CREATE TABLE IF NOT EXISTS public."Uzenet"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    kuldo_id integer NOT NULL,
    fogado_id integer,
    projekt_id integer,
    uzenet_tartalom text COLLATE pg_catalog."default" NOT NULL,
    allapot text COLLATE pg_catalog."default" DEFAULT 'elküldve'::text,
    kuldes_ideje timestamp without time zone DEFAULT now(),
    CONSTRAINT "Uzenet_pkey" PRIMARY KEY (id),
    CONSTRAINT "Uzenet_fogado_id_fkey" FOREIGN KEY (fogado_id)
        REFERENCES public."Felhasznalo" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "Uzenet_kuldo_id_fkey" FOREIGN KEY (kuldo_id)
        REFERENCES public."Felhasznalo" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "Uzenet_projekt_id_fkey" FOREIGN KEY (projekt_id)
        REFERENCES public."Projekt" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Uzenet"
    OWNER to postgres;
